/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.platosedu.app;

import io.platosedu.list.LinkedList;

import static io.platosedu.utilities.StringUtils.join;
import static io.platosedu.utilities.StringUtils.split;
import static io.platosedu.app.MessageUtils.getMessage;

public class App {
    public static void main(String[] args) {
        LinkedList tokens;
        tokens = split(getMessage());
        System.out.println(join(tokens));
    }
}
